#!/bin/bash
# SETTINGS AUTHENTICATION VERIFICATION CHECKLIST
# ================================================

echo "=================================================="
echo "VERIFICATION CHECKLIST: Is Settings Auth Working?"
echo "=================================================="
echo ""

echo "✓ STEP 1: User is LOGGED IN?"
echo "  How to check:"
echo "  1. Open browser → DevTools (F12)"
echo "  2. Go to Application tab"
echo "  3. Click Local Storage"
echo "  4. Look for 'token' key"
echo "     ✅ If 'token' exists with long string → Token is saved"
echo "     ❌ If 'token' is empty or missing → User not logged in"
echo ""

echo "✓ STEP 2: Is the Token being SENT with requests?"
echo "  How to check:"
echo "  1. In browser DevTools, go to Network tab"
echo "  2. Change a setting (e.g., toggle Email Notifications)"
echo "  3. Look for request like 'PUT users/me/settings/email_notifications'"
echo "  4. Click on it and check 'Request Headers'"
echo "  5. Look for: Authorization: Bearer eyJhbGc..."
echo "     ✅ If Authorization header exists → Interceptor works!"
echo "     ❌ If Authorization header missing → Interceptor not running"
echo ""

echo "✓ STEP 3: What's the HTTP Response Status?"
echo "  In Network tab, check the status code:"
echo "  ✅ 200 OK → Setting saved successfully!"
echo "  ✅ 201 Created → Setting created successfully!"
echo "  ❌ 401 Unauthorized → Token not sent OR token invalid"
echo "  ❌ 403 Forbidden → Authenticated but NOT admin (for /admin/settings)"
echo "  ❌ 400 Bad Request → Invalid setting value"
echo "  ❌ 404 Not Found → Endpoint not found"
echo ""

echo "✓ STEP 4: What does the Response Body say?"
echo "  Still in Network tab, go to Response tab:"
echo "  Success: { \"success\": true, \"updated_field\": \"email_notifications\", ... }"
echo "  Error: { \"detail\": \"Invalid or expired token\" }"
echo ""

echo "=================================================="
echo "COMMON SCENARIOS & SOLUTIONS"
echo "=================================================="
echo ""

echo "SCENARIO 1: 'Not authenticated' error"
echo "Causes:"
echo "  1. User not logged in → token is null"
echo "  2. Token not saved in localStorage"
echo "  3. Token expired (older than 30 days)"
echo ""
echo "Solution:"
echo "  1. Logout (clear localStorage)"
echo "  2. Login again with valid credentials"
echo "  3. Check localStorage has new token"
echo "  4. Try settings again"
echo ""

echo "SCENARIO 2: Authorization header NOT in request"
echo "Causes:"
echo "  1. api.js interceptor not loaded"
echo "  2. Vite dev server not restarted after code change"
echo "  3. Token not in localStorage"
echo ""
echo "Solution:"
echo "  1. Check if api.js has interceptor code"
echo "  2. Restart Vite dev server (npm run dev)"
echo "  3. Refresh browser (Ctrl+Shift+R for hard refresh)"
echo "  4. Login again"
echo ""

echo "SCENARIO 3: Settings load but update fails"
echo "Causes:"
echo "  1. Token sent but backend validation fails"
echo "  2. JWT signature mismatch"
echo "  3. Database connection issue"
echo ""
echo "Solution:"
echo "  1. Check backend logs (server terminal)"
echo "  2. Verify SECRET_KEY in .env matches server"
echo "  3. Restart backend server"
echo ""

echo "SCENARIO 4: Admin settings return 403 Forbidden"
echo "Causes:"
echo "  1. User is not Admin"
echo "  2. User role in database is 'Employee' not 'Admin'"
echo ""
echo "Solution:"
echo "  1. Login with admin account"
echo "  2. Or update user role in database:"
echo "     UPDATE users SET role='Admin' WHERE email='user@example.com';"
echo ""

echo "=================================================="
echo "HOW TO TEST MANUALLY"
echo "=================================================="
echo ""

echo "1. Open browser to http://localhost:5174"
echo "2. Login with credentials"
echo "3. Go to Settings page"
echo "4. Open DevTools (F12) → Network tab"
echo "5. Toggle a setting (Email Notifications, Theme, etc.)"
echo "6. Look at the request:"
echo ""
echo "   REQUEST SHOULD HAVE:"
echo "   POST /users/me/settings/email_notifications"
echo "   Header: Authorization: Bearer <token>"
echo "   Body: { \"value\": true }"
echo ""
echo "   RESPONSE SHOULD BE:"
echo "   200 OK"
echo "   { \"success\": true, \"updated_field\": \"email_notifications\", \"new_value\": true }"
echo ""

echo "7. If this works → ✅ AUTHENTICATION IS WORKING!"
echo "8. If not → Check scenarios above"
echo ""

echo "=================================================="
echo "DEBUG: Check localStorage"
echo "=================================================="
echo ""
echo "In browser console (F12 → Console tab), paste:"
echo ""
echo "  localStorage.getItem('token')"
echo ""
echo "Output should be:"
echo "  ✅ eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... (long string)"
echo "  ❌ null (not logged in)"
echo "  ❌ undefined (localStorage cleared)"
echo ""

echo "=================================================="
