export const shoutouts = [
  {
    id: 1,
    author: "Michael Chen",
    recipient: "Jessica Park",
    department: "Engineering",
    message: "Jessica absolutely crushed the sprint and delivered before deadline!",
    reactions: {
      hearts: 38,
      claps: 12,
      comments: 5,
    },
    status: "Pinned",
    date: "2026-02-17",
  },
  {
    id: 2,
    author: "Sarah Johnson",
    recipient: "David Kim",
    department: "Design",
    message: "David’s attention to detail made the UI perfect!",
    reactions: {
      hearts: 24,
      claps: 9,
      comments: 3,
    },
    status: "Active",
    date: "2026-02-17",
  },
  {
    id: 3,
    author: "Emily Rodriguez",
    recipient: "Alex Thompson",
    department: "Marketing",
    message: "Alex created an amazing campaign strategy!",
    reactions: {
      hearts: 42,
      claps: 15,
      comments: 8,
    },
    status: "Active",
    date: "2026-02-16",
  },
  {
    id: 4,
    author: "James Walker",
    recipient: "Olivia Brown",
    department: "Sales",
    message: "Closed the biggest deal of the quarter!",
    reactions: {
      hearts: 31,
      claps: 10,
      comments: 4,
    },
    status: "Archived",
    date: "2026-02-15",
  },
  {
    id: 5,
    author: "Sophia Martinez",
    recipient: "Daniel Lee",
    department: "HR",
    message: "Organized an incredible employee engagement event!",
    reactions: {
      hearts: 19,
      claps: 7,
      comments: 2,
    },
    status: "Active",
    date: "2026-02-14",
  },
  {
    id: 6,
    author: "William Clark",
    recipient: "Emma Wilson",
    department: "Engineering",
    message: "Refactored the legacy codebase beautifully.",
    reactions: {
      hearts: 27,
      claps: 14,
      comments: 6,
    },
    status: "Pinned",
    date: "2026-02-13",
  },
  {
    id: 7,
    author: "Isabella Moore",
    recipient: "Liam Anderson",
    department: "Design",
    message: "Created stunning illustrations for the new landing page.",
    reactions: {
      hearts: 22,
      claps: 11,
      comments: 5,
    },
    status: "Active",
    date: "2026-02-12",
  },
  {
    id: 8,
    author: "Noah Taylor",
    recipient: "Mia Thomas",
    department: "Marketing",
    message: "Improved SEO performance by 40% this month!",
    reactions: {
      hearts: 29,
      claps: 13,
      comments: 7,
    },
    status: "Archived",
    date: "2026-02-10",
  },
];